"""
app/models/patch.py
────────────────────
Represents the code fix (patch) generated by Claude.

After Claude analyzes the issue and the relevant source code,
it returns a patch — this model captures that response cleanly.
"""

from pydantic import BaseModel


class PatchModel(BaseModel):
    """
    A single file fix produced by the LLM.

    NOTE: For now, each run produces ONE patch for ONE file.
    Multi-file patching is a stretch goal for later.
    """

    file_path: str          # Relative path to the file being fixed
                            # e.g. "src/auth/login.py"

    original_code: str      # The original file content (before the fix)
                            # We store this so we can show a diff later

    patched_code: str       # The full file content after Claude's fix
                            # We write this directly to disk

    diff: str = ""          # The unified diff between original and patched
                            # Generated after patch is applied
                            # e.g. "--- a/login.py\n+++ b/login.py\n@@ ..."
